/**:
  ros__parameters:
    video_device: "/dev/video0"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "camera"
    pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
    av_device_format: "YUV422P"
    image_width: 1280
    image_height: 720
    camera_name: "test_camera"
    camera_info_url: "package://usb_cam/config/camera_info.yaml"
    brightness: 0
    contrast: 16
    saturation: 10
    sharpness: 7
    gain: 0
    auto_white_balance: true
    white_balance: 4000
    autoexposure: true
    exposure: 100
    autofocus: false
    focus: -1